server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/produtos/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/pedidos/**
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
